package bytebuddy.command;

import bytebuddy.storage.Storage;
import bytebuddy.task.TaskList;
import bytebuddy.ui.Ui;

/**
 * Represents a command that terminates the application.
 * <p>
 * When executed, this command signals that the program should exit
 * and returns a farewell message generated by the {@link Ui}.
 */
public class ByeCommand extends Command {

    /**
     * Creates a new {@code ByeCommand}.
     * <p>
     * This command is marked as an exit command by passing {@code true}
     * to the parent {@link Command} constructor.
     */
    public ByeCommand() {
        super(true);
    }

    /**
     * Executes the bye command.
     * <p>
     * This does not modify storage or the task list. Instead, it returns
     * a farewell message to the user through the {@link Ui}.
     *
     * @param storage The storage handler (unused for this command).
     * @param tasks   The task list (unused for this command).
     * @param ui      The UI component that provides the farewell message.
     * @return A string containing the farewell message.
     */
    @Override
    public String execute(Storage storage, TaskList tasks, Ui ui) {
        return ui.getFarewellMessage();
    }
}
